import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
export function ClusterCard({ cluster, datapoints, onApprove, onReject, onRename }) {
    const [draftLabel, setDraftLabel] = useState(cluster.label);
    const [isExpanded, setIsExpanded] = useState(false);
    const aliases = Array.isArray(cluster.metadata.aliases)
        ? cluster.metadata.aliases.filter((alias) => typeof alias === "string")
        : [];
    return (_jsxs("article", { className: `cluster-card ${isExpanded ? "is-expanded" : ""}`, children: [_jsxs("button", { type: "button", className: "cluster-card__toggle", onClick: () => setIsExpanded((current) => !current), children: [_jsxs("div", { className: "cluster-card__header", children: [_jsx("span", { className: `badge badge--${cluster.status}`, children: cluster.status }), _jsx("span", { className: "badge badge--type", children: cluster.type })] }), _jsx("strong", { children: cluster.label }), _jsxs("p", { children: [cluster.datapointCount, " datapoints"] }), _jsxs("small", { children: ["Updated ", new Date(cluster.updatedAt).toLocaleString()] })] }), _jsx("div", { className: "cluster-card__editor", children: _jsx("input", { value: draftLabel, onChange: (event) => setDraftLabel(event.target.value), onClick: (event) => event.stopPropagation() }) }), isExpanded ? (_jsxs("div", { className: "cluster-details", children: [_jsxs("div", { className: "cluster-details__section", children: [_jsx("h3", { children: "Aliases" }), aliases.length > 0 ? (_jsx("div", { className: "alias-chips", children: aliases.map((alias) => (_jsx("span", { className: "alias-chip", children: alias }, alias))) })) : (_jsx("p", { children: "No aliases stored for this cluster." }))] }), _jsxs("div", { className: "cluster-details__section", children: [_jsx("h3", { children: "Datapoints" }), _jsx("div", { className: "cluster-datapoints", children: datapoints.map((datapoint) => (_jsxs("div", { className: "cluster-datapoint", children: [_jsx("strong", { children: datapoint.rawName }), _jsx("span", { children: datapoint.identifier })] }, datapoint.id))) })] })] })) : null, _jsxs("div", { className: "cluster-card__actions", children: [_jsx("button", { type: "button", onClick: () => void onApprove(), children: "Approve" }), _jsx("button", { type: "button", onClick: () => void onReject(), children: "Reject" }), _jsx("button", { type: "button", onClick: () => void onRename(draftLabel), children: "Update" })] })] }));
}
